import '../styles/globals.css'
import { Inter } from 'next/font/google'
import React from "react"; 
import Head from "next/head"; 
// import { useNavigation } from 'next/navigation';
import Navbar from './components/Navbar';
import Footer from './components/Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  // const navigation = useNavigation();
  // const currentPath = navigation.currentPath;

  const meta = { 
    title : "First Contribution", 
    description : "website for beginners", 
    type: "website"
  }

  return (
    <html lang="en" className='scroll-smooth'>
      <Head>
        <title>{ meta.title }</title>
        <meta name="robots" content="follow, index" />
        <meta content={meta.description} name="description" />
      </Head>
      <main>
        <Navbar className="dark:bg-gray-800 w-full"/>
        <div className={inter.className}>{children}</div>
        <Footer />
      </main>
    </html>
  )
}
